# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoExample', '0014_auto_20170518_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to=b'%Y/%m/%d'),
        ),
    ]
