# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoExample', '0018_experiment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='user',
            field=models.TextField(null=True),
        ),
    ]
