# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoExample', '0021_experiment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='user',
        ),
        migrations.AddField(
            model_name='experiment',
            name='post',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='djangoExample.Post'),
            preserve_default=False,
        ),
    ]
