# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 05:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoExample', '0022_auto_20170522_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_float',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='number_positive',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='samplesheet',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
